// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uygulama.Models.DataContext;

namespace Uygulama.Migrations
{
    [DbContext(typeof(PiDataDBContext))]
    partial class PiDataDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Uygulama.Models.Models.Durum", b =>
                {
                    b.Property<int>("DurumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DurumAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DurumId");

                    b.ToTable("Durum");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Emlak", b =>
                {
                    b.Property<int>("EmlakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPosta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmlakAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KurulusTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yetkili")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmlakId");

                    b.ToTable("Emlak");
                });

            modelBuilder.Entity("Uygulama.Models.Models.IlanResim", b =>
                {
                    b.Property<int>("IlanResimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PortfoyId")
                        .HasColumnType("int");

                    b.Property<string>("ResimAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IlanResimId");

                    b.HasIndex("PortfoyId");

                    b.ToTable("IlanResim");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Ilceler", b =>
                {
                    b.Property<int>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("IlceAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.Property<int?>("SehirlerSehirId")
                        .HasColumnType("int");

                    b.HasKey("IlceId");

                    b.HasIndex("SehirlerSehirId");

                    b.ToTable("Ilceler");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Mahalleler", b =>
                {
                    b.Property<int>("MahalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.Property<int?>("IlcelerIlceId")
                        .HasColumnType("int");

                    b.Property<string>("MahalleAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MahalleId");

                    b.HasIndex("IlcelerIlceId");

                    b.ToTable("Mahalleler");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Musteri", b =>
                {
                    b.Property<int>("MusteriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EPosta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmlakId")
                        .HasColumnType("int");

                    b.Property<string>("GSM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MustKategori")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriId");

                    b.HasIndex("EmlakId");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Portfoy", b =>
                {
                    b.Property<int>("PortfoyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurumId")
                        .HasColumnType("int");

                    b.Property<double>("Fiyat")
                        .HasColumnType("float");

                    b.Property<string>("IlanBasligi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IlceId")
                        .HasColumnType("int");

                    b.Property<int>("Isınma")
                        .HasColumnType("int");

                    b.Property<string>("Kat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("MahalleId")
                        .HasColumnType("int");

                    b.Property<int?>("MahallelerMahalleId")
                        .HasColumnType("int");

                    b.Property<int>("MusteriId")
                        .HasColumnType("int");

                    b.Property<int>("OdaSayisi")
                        .HasColumnType("int");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.Property<int>("TipId")
                        .HasColumnType("int");

                    b.HasKey("PortfoyId");

                    b.HasIndex("MahallelerMahalleId");

                    b.HasIndex("MusteriId");

                    b.HasIndex("TipId");

                    b.ToTable("Portfoy");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Sehirler", b =>
                {
                    b.Property<int>("SehirId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SehirAd")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SehirId");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Tip", b =>
                {
                    b.Property<int>("TipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DurumId")
                        .HasColumnType("int");

                    b.Property<string>("TipAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipId");

                    b.HasIndex("DurumId");

                    b.ToTable("Tip");
                });

            modelBuilder.Entity("Uygulama.Models.Models.IlanResim", b =>
                {
                    b.HasOne("Uygulama.Models.Models.Portfoy", "Portfoy")
                        .WithMany("IlanResims")
                        .HasForeignKey("PortfoyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfoy");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Ilceler", b =>
                {
                    b.HasOne("Uygulama.Models.Models.Sehirler", "Sehirler")
                        .WithMany("Ilcelers")
                        .HasForeignKey("SehirlerSehirId");

                    b.Navigation("Sehirler");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Mahalleler", b =>
                {
                    b.HasOne("Uygulama.Models.Models.Ilceler", "Ilceler")
                        .WithMany("Mahallelers")
                        .HasForeignKey("IlcelerIlceId");

                    b.Navigation("Ilceler");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Musteri", b =>
                {
                    b.HasOne("Uygulama.Models.Models.Emlak", "Emlak")
                        .WithMany("Musteris")
                        .HasForeignKey("EmlakId");

                    b.Navigation("Emlak");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Portfoy", b =>
                {
                    b.HasOne("Uygulama.Models.Models.Mahalleler", "Mahalleler")
                        .WithMany()
                        .HasForeignKey("MahallelerMahalleId");

                    b.HasOne("Uygulama.Models.Models.Musteri", "Musteri")
                        .WithMany("Portfoys")
                        .HasForeignKey("MusteriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Uygulama.Models.Models.Tip", "Tip")
                        .WithMany()
                        .HasForeignKey("TipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mahalleler");

                    b.Navigation("Musteri");

                    b.Navigation("Tip");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Tip", b =>
                {
                    b.HasOne("Uygulama.Models.Models.Durum", "Durum")
                        .WithMany("Tips")
                        .HasForeignKey("DurumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Durum");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Durum", b =>
                {
                    b.Navigation("Tips");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Emlak", b =>
                {
                    b.Navigation("Musteris");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Ilceler", b =>
                {
                    b.Navigation("Mahallelers");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Musteri", b =>
                {
                    b.Navigation("Portfoys");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Portfoy", b =>
                {
                    b.Navigation("IlanResims");
                });

            modelBuilder.Entity("Uygulama.Models.Models.Sehirler", b =>
                {
                    b.Navigation("Ilcelers");
                });
#pragma warning restore 612, 618
        }
    }
}
